package eu.ehealth;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by Apache CXF 2.7.8 2013-12-20T15:49:23.316+01:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://ehealth.eu/StorageComponent/", name = "StorageComponent")
public interface StorageComponent
{
	
	
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "CreateRule", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.CreateRule")
	@WebMethod(operationName = "CreateRule", action = "http://ehealth.eu/StorageComponent/CreateRule")
	@ResponseWrapper(localName = "CreateRuleResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.CreateRuleResponse")
	public eu.ehealth.db.xsd.OperationResult createRules(
			@WebParam(name = "data", targetNamespace = "") eu.ehealth.db.xsd.Rules data,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);
	

	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "UpdateRule", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.UpdateRule")
	@WebMethod(operationName = "UpdateRule", action = "http://ehealth.eu/StorageComponent/UpdateRule")
	@ResponseWrapper(localName = "UpdateRuleResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.UpdateRuleResponse")
	public eu.ehealth.db.xsd.OperationResult updateRules(
			@WebParam(name = "data", targetNamespace = "") eu.ehealth.db.xsd.Rules data,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);
	
	
	/**
	 * 
	 * @return
	 */
	public String[] getStatus();
	
	
	/**
	 * 
	 * @param id
	 */
	public String initDB(String id);
	//public void init();


	/**
	 * registerUser (user, pass, userId) 
	 */
	public String[] registerUser(String userName, String password, String userId);
	
	
	/**
	 * login  (user, pass) 
	 */
	public String[] login(String userName, String password);
	
	
	/**
	 * 
	 * @param idUser
	 * @param sessionId
	 * @return
	 */
	public void logout(String idUser, String sessionId);
	
	
	/**
	 * 
	 * @param idUser
	 * @return
	 */
	public Object[] getConnectedUsers(String idUser);
	
	
	/**
	 * lockout  (user)
	 */
	public String[] lockout(String userName);
	
	
	/**
	 * 
	 * @return
	 */
	public List<String[]> getEhealthRoles();
	
	
	/**
	 * 
	 * @return
	 */
	public List<String[]> getEhealthParameters();
	
	
	/**
	 * 
	 * @param userId
	 * @return
	 */
	public List<String[]> getAppConfig(String userId);
	
	
	/**
	 * 
	 * @param userId
	 * @return
	 */
	public List<String[]> listOfUsers(String userId);
	
	
	/**
	 * 
	 * @param userId
	 * @param id
	 * @param locked
	 * @return
	 */
	public eu.ehealth.db.xsd.OperationResult lockUser(String userId, int id, boolean locked);
	
	
	/**
	 * 
	 * @param userId
	 * @param id
	 * @param value
	 * @param active
	 * @return
	 */
	public eu.ehealth.db.xsd.OperationResult updateAppConfigRow(String userId, int id, String value, boolean active);
	
	
	/**
	 * The GetUserIdByAdminId method receives a person’s identity and returns corresponded user id or an error-code.
	 */
	public eu.ehealth.db.xsd.OperationResult getUserIdByAdminId(String id, String userId);
	
	
	/**
	 * The GetUserIdByCarerId method receives a person’s identity and returns corresponded user id or an error-code.
	 */
	public eu.ehealth.db.xsd.OperationResult getUserIdByCarerId(String id, String userId);
	
	
	/**
	 * The GetUserIdByClinicianId method receives a person’s identity and returns corresponded user id or an error-code.
	 */
	public eu.ehealth.db.xsd.OperationResult getUserIdByClinicianId(String id, String userId);
	
	
	/**
	 * The getUserIdByPatientId method receives a person’s identity and returns corresponded user id or an error-code.
	 */
	public eu.ehealth.db.xsd.OperationResult getUserIdByPatientId(String id, String userId);
	
	
	/**
	 * The getUserIdByPatientId method receives a person’s identity and returns corresponded user id or an error-code.
	 */
	public eu.ehealth.db.xsd.OperationResult getUserPersonIdByPatientId(String id, String userId);
	
	
	/**
	 * Get type of the user by its id.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "GetUserType", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetUserType")
	@WebMethod(operationName = "GetUserType", action = "http://ehealth.eu/StorageComponent/GetUserType")
	@ResponseWrapper(localName = "GetUserTypeResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetUserTypeResponse")
	public eu.ehealth.db.xsd.OperationResult getUserType(
			@WebParam(name = "id", targetNamespace = "") java.lang.String id);


	/**
	 * The DeleteAdministrator method deletes an existing administrator record
	 * (administrator is identified by “id”). It returns the administrator’s
	 * identity from the database or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "DeleteAdministrator", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.DeleteAdministrator")
	@WebMethod(operationName = "DeleteAdministrator", action = "http://ehealth.eu/StorageComponent/DeleteAdministrator")
	@ResponseWrapper(localName = "DeleteAdministratorResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.DeleteAdministratorResponse")
	public eu.ehealth.db.xsd.OperationResult deleteAdministrator(
			@WebParam(name = "id", targetNamespace = "") java.lang.String id,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The UpdateSystemParametermethod updates the system parameter. It returns
	 * the parameter id in the database or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "UpdateSystemParameter", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.UpdateSystemParameter")
	@WebMethod(operationName = "UpdateSystemParameter", action = "http://ehealth.eu/StorageComponent/UpdateSystemParameter")
	@ResponseWrapper(localName = "UpdateSystemParameterResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.UpdateSystemParameterResponse")
	public eu.ehealth.db.xsd.OperationResult updateSystemParameter(
			@WebParam(name = "type", targetNamespace = "") int type,
			@WebParam(name = "value", targetNamespace = "") eu.ehealth.db.xsd.SystemParameter value,
			@WebParam(name = "locale", targetNamespace = "") eu.ehealth.db.xsd.SystemParameter locale);


	/**
	 * The GetSystemParameterListreturns the list of the system parameter of
	 * given type and for given locale.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "GetSystemParameterList", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetSystemParameterList")
	@WebMethod(operationName = "GetSystemParameterList", action = "http://ehealth.eu/StorageComponent/GetSystemParameterList")
	@ResponseWrapper(localName = "GetSystemParameterListResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetSystemParameterListResponse")
	public java.util.List<eu.ehealth.db.xsd.SystemParameter> getSystemParameterList(
			@WebParam(name = "type", targetNamespace = "") int type,
			@WebParam(name = "locale", targetNamespace = "") eu.ehealth.db.xsd.SystemParameter locale);


	/**
	 * The DeletePatient method deletes an existing patient record (patient
	 * identified by “id”). It returns the patient’s identity from the database
	 * or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "GetPatient", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetPatient")
	@WebMethod(operationName = "GetPatient", action = "http://ehealth.eu/StorageComponent/GetPatient")
	@ResponseWrapper(localName = "GetPatientResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetPatientResponse")
	public eu.ehealth.db.xsd.Patient getPatient(
			@WebParam(name = "id", targetNamespace = "") java.lang.String id,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The DeletePatient method deletes an existing patient record (patient
	 * identified by “id”). It returns the patient’s identity from the database
	 * or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "DeletePatient", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.DeletePatient")
	@WebMethod(operationName = "DeletePatient", action = "http://ehealth.eu/StorageComponent/DeletePatient")
	@ResponseWrapper(localName = "DeletePatientResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.DeletePatientResponse")
	public eu.ehealth.db.xsd.OperationResult deletePatient(
			@WebParam(name = "id", targetNamespace = "") java.lang.String id,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The AddMediaContent method adds the media content in the database. It
	 * returns the media content id in the database or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "AddMediaContent", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.AddMediaContent")
	@WebMethod(operationName = "AddMediaContent", action = "http://ehealth.eu/StorageComponent/AddMediaContent")
	@ResponseWrapper(localName = "AddMediaContentResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.AddMediaContentResponse")
	public eu.ehealth.db.xsd.OperationResult addMediaContent(
			@WebParam(name = "in", targetNamespace = "") eu.ehealth.db.xsd.MediaContent in,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The ChangePassword method updates the password for the user identified by
	 * “userId”, if the requestor identified by “requestorId” has permissions
	 * for that. The method returns a confirmation code or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "ChangePassword", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.ChangePassword")
	@WebMethod(operationName = "ChangePassword", action = "http://ehealth.eu/StorageComponent/ChangePassword")
	@ResponseWrapper(localName = "ChangePasswordResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.ChangePasswordResponse")
	public eu.ehealth.db.xsd.OperationResult changePassword(
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId,
			@WebParam(name = "password", targetNamespace = "") java.lang.String password,
			@WebParam(name = "reqId", targetNamespace = "") java.lang.String reqId);


	/**
	 * The GetQuestionDescription method gets description of the question by its
	 * id from the database. It returns the value or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "GetQuestionDescription", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetQuestionDescription")
	@WebMethod(operationName = "GetQuestionDescription", action = "http://ehealth.eu/StorageComponent/GetQuestionDescription")
	@ResponseWrapper(localName = "GetQuestionDescriptionResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetQuestionDescriptionResponse")
	public eu.ehealth.db.xsd.OperationResult getQuestionDescription(
			@WebParam(name = "questionID", targetNamespace = "") java.lang.String questionID,
			@WebParam(name = "locale", targetNamespace = "") eu.ehealth.db.xsd.SystemParameter locale);


	/**
	 * The ListOfClinicians method selects a list of clinicians from database
	 * using “filter” (“filter” can restrict various parameters of clinician’s
	 * profile such as name, age, id, etc.).
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "ListOfClinicians", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.ListOfClinicians")
	@WebMethod(operationName = "ListOfClinicians", action = "http://ehealth.eu/StorageComponent/ListOfClinicians")
	@ResponseWrapper(localName = "ListOfCliniciansResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.ListOfCliniciansResponse")
	public java.util.List<eu.ehealth.db.xsd.ClinicianInfo> listOfClinicians(
			@WebParam(name = "filter", targetNamespace = "") java.util.List<eu.ehealth.db.xsd.SearchCriteria> filter,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The GetMeasurement method filters measurements by its parameters and
	 * return the list of filtered items.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "GetMeasurement", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetMeasurement")
	@WebMethod(operationName = "GetMeasurement", action = "http://ehealth.eu/StorageComponent/GetMeasurement")
	@ResponseWrapper(localName = "GetMeasurementResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetMeasurementResponse")
	public java.util.List<eu.ehealth.db.xsd.Measurement> getMeasurement(
			@WebParam(name = "filter", targetNamespace = "") java.util.List<eu.ehealth.db.xsd.SearchCriteria> filter,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The UpdateUser method receives a user’s data (data) and updates it in the
	 * database. It returns a confirmation code or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "UpdateUser", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.UpdateUser")
	@WebMethod(operationName = "UpdateUser", action = "http://ehealth.eu/StorageComponent/UpdateUser")
	@ResponseWrapper(localName = "UpdateUserResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.UpdateUserResponse")
	public eu.ehealth.db.xsd.OperationResult updateUser(
			@WebParam(name = "user", targetNamespace = "") eu.ehealth.db.xsd.User user);


	/**
	 * The DeleteExternalService method deletes an existing external service
	 * record (service is identified by “id”). It returns service’s identity
	 * from the database or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "DeleteExternalService", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.DeleteExternalService")
	@WebMethod(operationName = "DeleteExternalService", action = "http://ehealth.eu/StorageComponent/DeleteExternalService")
	@ResponseWrapper(localName = "DeleteExternalServiceResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.DeleteExternalServiceResponse")
	public eu.ehealth.db.xsd.OperationResult deleteExternalService(
			@WebParam(name = "id", targetNamespace = "") java.lang.String id,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The DeleteUser method receives a user’s data (user) and deletes it from
	 * database. It returns a confirmation code or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "DeleteUser", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.DeleteUser")
	@WebMethod(operationName = "DeleteUser", action = "http://ehealth.eu/StorageComponent/DeleteUser")
	@ResponseWrapper(localName = "DeleteUserResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.DeleteUserResponse")
	public eu.ehealth.db.xsd.OperationResult deleteUser(
			@WebParam(name = "id", targetNamespace = "") java.lang.String id);


	/**
	 * The GetQuestionnaireAnswersByTask method gets QuestionnaireAnswers value
	 * for the given task from the database.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "GetQuestionnaireAnswersByTask", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetQuestionnaireAnswersByTask")
	@WebMethod(operationName = "GetQuestionnaireAnswersByTask", action = "http://ehealth.eu/StorageComponent/GetQuestionnaireAnswersByTask")
	@ResponseWrapper(localName = "GetQuestionnaireAnswersByTaskResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetQuestionnaireAnswersByTaskResponse")
	public eu.ehealth.db.xsd.QuestionnaireAnswers getQuestionnaireAnswersByTask(
			@WebParam(name = "taskId", targetNamespace = "") java.lang.String taskId,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The GetCarerAssessments method receives the carer’s identity (“id”) and
	 * returns her/his assessment’s data or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "GetCarerAssessments", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetCarerAssessments")
	@WebMethod(operationName = "GetCarerAssessments", action = "http://ehealth.eu/StorageComponent/GetCarerAssessments")
	@ResponseWrapper(localName = "GetCarerAssessmentsResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetCarerAssessmentsResponse")
	public java.util.List<eu.ehealth.db.xsd.CarerAssessment> getCarerAssessments(
			@WebParam(name = "carerId", targetNamespace = "") java.lang.String carerId,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The SavePatientAssessment method receives the assessment data for a
	 * patient (”assessment”), stores it in the database and returns the
	 * assessment’s identity or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "SavePatientAssessment", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.SavePatientAssessment")
	@WebMethod(operationName = "SavePatientAssessment", action = "http://ehealth.eu/StorageComponent/SavePatientAssessment")
	@ResponseWrapper(localName = "SavePatientAssessmentResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.SavePatientAssessmentResponse")
	public eu.ehealth.db.xsd.OperationResult savePatientAssessment(
			@WebParam(name = "assessment", targetNamespace = "") eu.ehealth.db.xsd.PatientAssessment assessment,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The GetMediaContent method gets the media content from the database by
	 * its id.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "GetMediaContent", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetMediaContent")
	@WebMethod(operationName = "GetMediaContent", action = "http://ehealth.eu/StorageComponent/GetMediaContent")
	@ResponseWrapper(localName = "GetMediaContentResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetMediaContentResponse")
	public java.util.List<eu.ehealth.db.xsd.MediaContent> getMediaContent(
			@WebParam(name = "filter", targetNamespace = "") java.util.List<eu.ehealth.db.xsd.SearchCriteria> filter,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The ListOfQuestionnaires method returns a list of short descriptions of
	 * the available questionnaires.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "ListOfQuestionnaires", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.ListOfQuestionnaires")
	@WebMethod(operationName = "ListOfQuestionnaires", action = "http://ehealth.eu/StorageComponent/ListOfQuestionnaires")
	@ResponseWrapper(localName = "ListOfQuestionnairesResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.ListOfQuestionnairesResponse")
	public java.util.List<eu.ehealth.db.xsd.QuestionnaireInfo> listOfQuestionnaires(
			@WebParam(name = "locale", targetNamespace = "") eu.ehealth.db.xsd.SystemParameter locale,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The SaveWarning method receives the warning’s data and stores it in the
	 * database. It returns the warning id in the database or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "SaveWarning", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.SaveWarning")
	@WebMethod(operationName = "SaveWarning", action = "http://ehealth.eu/StorageComponent/SaveWarning")
	@ResponseWrapper(localName = "SaveWarningResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.SaveWarningResponse")
	public eu.ehealth.db.xsd.OperationResult saveWarning(
			@WebParam(name = "warn", targetNamespace = "") eu.ehealth.db.xsd.Warning warn,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The CreateQuestionnaire method saves a new questionnaire in the database.
	 * It returns a confirmation code or an error code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "CreateQuestionnaire", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.CreateQuestionnaire")
	@WebMethod(operationName = "CreateQuestionnaire", action = "http://ehealth.eu/StorageComponent/CreateQuestionnaire")
	@ResponseWrapper(localName = "CreateQuestionnaireResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.CreateQuestionnaireResponse")
	public eu.ehealth.db.xsd.OperationResult createQuestionnaire(
			@WebParam(name = "data", targetNamespace = "") eu.ehealth.db.xsd.Questionnaire data,
			@WebParam(name = "locale", targetNamespace = "") eu.ehealth.db.xsd.SystemParameter locale,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The UpdateCarer method updates an existing record for carer using “data”.
	 * It returns the carer’s identity in the database or error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "UpdateCarer", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.UpdateCarer")
	@WebMethod(operationName = "UpdateCarer", action = "http://ehealth.eu/StorageComponent/UpdateCarer")
	@ResponseWrapper(localName = "UpdateCarerResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.UpdateCarerResponse")
	public eu.ehealth.db.xsd.OperationResult updateCarer(
			@WebParam(name = "data", targetNamespace = "") eu.ehealth.db.xsd.Carer data,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The GetUserIdByPersonId method receives a person’s identity and person’s
	 * type and returns corresponded user id or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "GetUserIdByPersonId", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetUserIdByPersonId")
	@WebMethod(operationName = "GetUserIdByPersonId", action = "http://ehealth.eu/StorageComponent/GetUserIdByPersonId")
	@ResponseWrapper(localName = "GetUserIdByPersonIdResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetUserIdByPersonIdResponse")
	public eu.ehealth.db.xsd.OperationResult getUserIdByPersonId(
			@WebParam(name = "id", targetNamespace = "") java.lang.String id,
			@WebParam(name = "type", targetNamespace = "") int type,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The UpdateQuestionnaire method updates the description of an existing
	 * questionnaire in the database. It returns a confirmation code or an error
	 * code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "UpdateQuestionnaire", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.UpdateQuestionnaire")
	@WebMethod(operationName = "UpdateQuestionnaire", action = "http://ehealth.eu/StorageComponent/UpdateQuestionnaire")
	@ResponseWrapper(localName = "UpdateQuestionnaireResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.UpdateQuestionnaireResponse")
	public eu.ehealth.db.xsd.OperationResult updateQuestionnaire(
			@WebParam(name = "data", targetNamespace = "") eu.ehealth.db.xsd.Questionnaire data,
			@WebParam(name = "locale", targetNamespace = "") eu.ehealth.db.xsd.SystemParameter locale,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The ListOfCarers method selects a list of carers from database using
	 * “filter” (“filter” can restrict various parameters of carer’s profile
	 * such as name, age, id, etc.).
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "ListOfCarers", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.ListOfCarers")
	@WebMethod(operationName = "ListOfCarers", action = "http://ehealth.eu/StorageComponent/ListOfCarers")
	@ResponseWrapper(localName = "ListOfCarersResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.ListOfCarersResponse")
	public java.util.List<eu.ehealth.db.xsd.CarerInfo> listOfCarers(
			@WebParam(name = "filter", targetNamespace = "") java.util.List<eu.ehealth.db.xsd.SearchCriteria> filter,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The DeleteClinician method deletes an existing clinician record
	 * (clinician is identified by “id”). It returns the clinician’s identity
	 * from the database or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "DeleteClinician", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.DeleteClinician")
	@WebMethod(operationName = "DeleteClinician", action = "http://ehealth.eu/StorageComponent/DeleteClinician")
	@ResponseWrapper(localName = "DeleteClinicianResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.DeleteClinicianResponse")
	public eu.ehealth.db.xsd.OperationResult deleteClinician(
			@WebParam(name = "id", targetNamespace = "") java.lang.String id,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The GetQuestionnaireAnswers method returns from the database the
	 * questionnaire answers about the person with a given ID (ObjectId) for the
	 * requested date range (fromDate, toDate)
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "GetQuestionnaireAnswers", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetQuestionnaireAnswers")
	@WebMethod(operationName = "GetQuestionnaireAnswers", action = "http://ehealth.eu/StorageComponent/GetQuestionnaireAnswers")
	@ResponseWrapper(localName = "GetQuestionnaireAnswersResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetQuestionnaireAnswersResponse")
	public java.util.List<eu.ehealth.db.xsd.QuestionnaireAnswers> getQuestionnaireAnswers(
			@WebParam(name = "ObjectId", targetNamespace = "") java.lang.String objectId,
			@WebParam(name = "fromDate", targetNamespace = "") javax.xml.datatype.XMLGregorianCalendar fromDate,
			@WebParam(name = "toDate", targetNamespace = "") javax.xml.datatype.XMLGregorianCalendar toDate,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The StoreMeasurements method receives an array of measurements (data) and
	 * stores it in the database. It returns a new record’s identity or an
	 * error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "StoreMeasurements", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.StoreMeasurements")
	@WebMethod(operationName = "StoreMeasurements", action = "http://ehealth.eu/StorageComponent/StoreMeasurements")
	@ResponseWrapper(localName = "StoreMeasurementsResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.StoreMeasurementsResponse")
	public eu.ehealth.db.xsd.OperationResult storeMeasurements(
			@WebParam(name = "data", targetNamespace = "") java.util.List<eu.ehealth.db.xsd.Measurement> data,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The AssignTasksMassivelymethod creates a number of task for the given
	 * period of time and with given frequency. It returns the id of the last
	 * task in the database or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "AssignTasksMassively", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.AssignTasksMassively")
	@WebMethod(operationName = "AssignTasksMassively", action = "http://ehealth.eu/StorageComponent/AssignTasksMassively")
	@ResponseWrapper(localName = "AssignTasksMassivelyResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.AssignTasksMassivelyResponse")
	public eu.ehealth.db.xsd.OperationResult assignTasksMassively(
			@WebParam(name = "task", targetNamespace = "") eu.ehealth.db.xsd.Task task,
			@WebParam(name = "startDate", targetNamespace = "") javax.xml.datatype.XMLGregorianCalendar startDate,
			@WebParam(name = "endDate", targetNamespace = "") javax.xml.datatype.XMLGregorianCalendar endDate,
			@WebParam(name = "frequency", targetNamespace = "") java.math.BigInteger frequency,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The getAvailableCarers method returns list of carers that are not binded
	 * for the any patient.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "getAvailableCarers", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetAvailableCarers")
	@WebMethod(action = "http://ehealth.eu/StorageComponent/getAvailableCarers")
	@ResponseWrapper(localName = "getAvailableCarersResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetAvailableCarersResponse")
	public java.util.List<eu.ehealth.db.xsd.CarerInfo> getAvailableCarers(
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The Auth method performs the user’s authentication based on login and
	 * password. It returns a user’s id in case of success, error-code
	 * otherwise.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "Auth", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.Auth")
	@WebMethod(operationName = "Auth", action = "http://ehealth.eu/StorageComponent/Auth")
	@ResponseWrapper(localName = "AuthResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.AuthResponse")
	public eu.ehealth.db.xsd.OperationResult auth(
			@WebParam(name = "login", targetNamespace = "") java.lang.String login,
			@WebParam(name = "password", targetNamespace = "") java.lang.String password,
			@WebParam(name = "token", targetNamespace = "") java.lang.String token);


	/**
	 * The DeleteCarerAssessment method deletes an existing assessment from the
	 * database (assessment is identified by assessmentId), returns the
	 * assessment’s identity or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "DeleteCarerAssessment", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.DeleteCarerAssessment")
	@WebMethod(operationName = "DeleteCarerAssessment", action = "http://ehealth.eu/StorageComponent/DeleteCarerAssessment")
	@ResponseWrapper(localName = "DeleteCarerAssessmentResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.DeleteCarerAssessmentResponse")
	public eu.ehealth.db.xsd.OperationResult deleteCarerAssessment(
			@WebParam(name = "assessmentId", targetNamespace = "") java.lang.String assessmentId,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The CreateClinician method creates a new record for the clinician using
	 * “data”. It returns the clinician’s identity from the database or an
	 * error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "CreateClinician", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.CreateClinician")
	@WebMethod(operationName = "CreateClinician", action = "http://ehealth.eu/StorageComponent/CreateClinician")
	@ResponseWrapper(localName = "CreateClinicianResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.CreateClinicianResponse")
	public eu.ehealth.db.xsd.OperationResult createClinician(
			@WebParam(name = "data", targetNamespace = "") eu.ehealth.db.xsd.Clinician data,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The UpdateMediaContent method updates the media content in the database.
	 * It returns the media content id in the database or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "UpdateMediaContent", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.UpdateMediaContent")
	@WebMethod(operationName = "UpdateMediaContent", action = "http://ehealth.eu/StorageComponent/UpdateMediaContent")
	@ResponseWrapper(localName = "UpdateMediaContentResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.UpdateMediaContentResponse")
	public eu.ehealth.db.xsd.OperationResult updateMediaContent(
			@WebParam(name = "ec", targetNamespace = "") eu.ehealth.db.xsd.MediaContent ec,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The GetPatientsForCaregiver returns the list of patient for that this is
	 * caregiver is responded.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "GetPatientsForCaregiver", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetPatientsForCaregiver")
	@WebMethod(operationName = "GetPatientsForCaregiver", action = "http://ehealth.eu/StorageComponent/GetPatientsForCaregiver")
	@ResponseWrapper(localName = "GetPatientsForCaregiverResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetPatientsForCaregiverResponse")
	public java.util.List<eu.ehealth.db.xsd.PatientInfo> getPatientsForCaregiver(
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The ListOfPossibleTasks method receives the user type (userType) and
	 * returns a list of permitted tasks for this user type.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "ListOfPossibleTasks", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.ListOfPossibleTasks")
	@WebMethod(operationName = "ListOfPossibleTasks", action = "http://ehealth.eu/StorageComponent/ListOfPossibleTasks")
	@ResponseWrapper(localName = "ListOfPossibleTasksResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.ListOfPossibleTasksResponse")
	public java.util.List<eu.ehealth.db.xsd.SystemParameter> listOfPossibleTasks(
			@WebParam(name = "userType", targetNamespace = "") int userType);


	/**
	 * The StoreQuestionnaireAnswers method receives the answers for a
	 * questionnaire (“data”) and stores them in the database. It returns a new
	 * record’s identity or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "StoreQuestionnaireAnswers", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.StoreQuestionnaireAnswers")
	@WebMethod(operationName = "StoreQuestionnaireAnswers", action = "http://ehealth.eu/StorageComponent/StoreQuestionnaireAnswers")
	@ResponseWrapper(localName = "StoreQuestionnaireAnswersResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.StoreQuestionnaireAnswersResponse")
	public eu.ehealth.db.xsd.OperationResult storeQuestionnaireAnswers(
			@WebParam(name = "data", targetNamespace = "") eu.ehealth.db.xsd.QuestionnaireAnswers data,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The GetCarer method selects a carer from database using “id”.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "GetCarer", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetCarer")
	@WebMethod(operationName = "GetCarer", action = "http://ehealth.eu/StorageComponent/GetCarer")
	@ResponseWrapper(localName = "GetCarerResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetCarerResponse")
	public eu.ehealth.db.xsd.Carer getCarer(
			@WebParam(name = "id", targetNamespace = "") java.lang.String id,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The ListOfAdministrators method selects a list of administrators from
	 * database using “filter” (“filter” can restrict various parameters of the
	 * administrator’s profile, such as name, id, etc.).
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "ListOfAdministrators", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.ListOfAdministrators")
	@WebMethod(operationName = "ListOfAdministrators", action = "http://ehealth.eu/StorageComponent/ListOfAdministrators")
	@ResponseWrapper(localName = "ListOfAdministratorsResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.ListOfAdministratorsResponse")
	public java.util.List<eu.ehealth.db.xsd.AdministratorInfo> listOfAdministrators(
			@WebParam(name = "filter", targetNamespace = "") java.util.List<eu.ehealth.db.xsd.SearchCriteria> filter,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The CreateAdministrator method creates a new record for the administrator
	 * using “data”. It returns the administrator’s identity from the database
	 * or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "CreateAdministrator", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.CreateAdministrator")
	@WebMethod(operationName = "CreateAdministrator", action = "http://ehealth.eu/StorageComponent/CreateAdministrator")
	@ResponseWrapper(localName = "CreateAdministratorResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.CreateAdministratorResponse")
	public eu.ehealth.db.xsd.OperationResult createAdministrator(
			@WebParam(name = "data", targetNamespace = "") eu.ehealth.db.xsd.Administrator data,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The UpdateExternalService method updates an existing record for the
	 * external service using “data”. It returns the service’s identity from the
	 * database or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "UpdateExternalService", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.UpdateExternalService")
	@WebMethod(operationName = "UpdateExternalService", action = "http://ehealth.eu/StorageComponent/UpdateExternalService")
	@ResponseWrapper(localName = "UpdateExternalServiceResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.UpdateExternalServiceResponse")
	public eu.ehealth.db.xsd.OperationResult updateExternalService(
			@WebParam(name = "data", targetNamespace = "") eu.ehealth.db.xsd.ExternalService data,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The GetPatientMeasurements method receives the patient’s identity
	 * (PatientId), the measurement’s type (MeasurementType), the date range
	 * (fromDate, toDate) and returns the corresponding records from the
	 * database.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "GetPatientMeasurement", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetPatientMeasurement")
	@WebMethod(operationName = "GetPatientMeasurement", action = "http://ehealth.eu/StorageComponent/GetPatientMeasurement")
	@ResponseWrapper(localName = "GetPatientMeasurementResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetPatientMeasurementResponse")
	public java.util.List<eu.ehealth.db.xsd.Measurement> getPatientMeasurement(
			@WebParam(name = "PatientId", targetNamespace = "") java.lang.String patientId,
			@WebParam(name = "MeasurementType", targetNamespace = "") int measurementType,
			@WebParam(name = "fromData", targetNamespace = "") javax.xml.datatype.XMLGregorianCalendar fromData,
			@WebParam(name = "toData", targetNamespace = "") javax.xml.datatype.XMLGregorianCalendar toData,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The DeleteCarer method deletes an existing record for the carer (carer is
	 * identified by “id”). It returns carer’s identity from the database or an
	 * error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "DeleteCarer", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.DeleteCarer")
	@WebMethod(operationName = "DeleteCarer", action = "http://ehealth.eu/StorageComponent/DeleteCarer")
	@ResponseWrapper(localName = "DeleteCarerResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.DeleteCarerResponse")
	public eu.ehealth.db.xsd.OperationResult deleteCarer(
			@WebParam(name = "id", targetNamespace = "") java.lang.String id,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The GetExternalService method selects all external services from the
	 * database.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "GetAllExternalServices", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetAllExternalServices")
	@WebMethod(operationName = "GetAllExternalServices", action = "http://ehealth.eu/StorageComponent/GetAllExternalServices")
	@ResponseWrapper(localName = "GetAllExternalServicesResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetAllExternalServicesResponse")
	public java.util.List<eu.ehealth.db.xsd.ExternalService> getAllExternalServices(
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The GetWarnings method returns the warnings from the database using
	 * “filter” (“filter” can restrict various parameters of the warning, such
	 * as risk level, patient, etc.).
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "GetWarnings", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetWarnings")
	@WebMethod(operationName = "GetWarnings", action = "http://ehealth.eu/StorageComponent/GetWarnings")
	@ResponseWrapper(localName = "GetWarningsResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetWarningsResponse")
	public java.util.List<eu.ehealth.db.xsd.Warning> getWarnings(
			@WebParam(name = "warn", targetNamespace = "") java.util.List<eu.ehealth.db.xsd.SearchCriteria> warn,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The ListOfPatients method selects a list of patients from the database
	 * using “filter” (“filter” can restrict various parameters of the patient’s
	 * profile such as name, age, id, etc.).
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "ListOfPatients", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.ListOfPatients")
	@WebMethod(operationName = "ListOfPatients", action = "http://ehealth.eu/StorageComponent/ListOfPatients")
	@ResponseWrapper(localName = "ListOfPatientsResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.ListOfPatientsResponse")
	public java.util.List<eu.ehealth.db.xsd.PatientInfo> listOfPatients(
			@WebParam(name = "filter", targetNamespace = "") java.util.List<eu.ehealth.db.xsd.SearchCriteria> filter,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);
	
	
	/**
	 * The ListOfPatients method selects a list of patients from the database
	 * using “filter” (“filter” can restrict various parameters of the patient’s
	 * profile such as name, age, id, etc.).
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "ListOfPatientsFromDoctor", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.ListOfPatientsFromDoctor")
	@WebMethod(operationName = "ListOfPatientsFromDoctor", action = "http://ehealth.eu/StorageComponent/ListOfPatientsFromDoctor")
	@ResponseWrapper(localName = "ListOfPatientsFromDoctorResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.ListOfPatientsFromDoctorResponse")
	public java.util.List<eu.ehealth.db.xsd.PatientInfo> listOfPatientsFromDoctor(
			@WebParam(name = "filter", targetNamespace = "") java.util.List<eu.ehealth.db.xsd.SearchCriteria> filter,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId,
			@WebParam(name = "clinicianId", targetNamespace = "") java.lang.String clinicianId);


	/**
	 * The UpdateClinician method updates an existing clinician record using
	 * “data”. It returns the clinician’s identity from the database or an
	 * error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "UpdateClinician", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.UpdateClinician")
	@WebMethod(operationName = "UpdateClinician", action = "http://ehealth.eu/StorageComponent/UpdateClinician")
	@ResponseWrapper(localName = "UpdateClinicianResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.UpdateClinicianResponse")
	public eu.ehealth.db.xsd.OperationResult updateClinician(
			@WebParam(name = "data", targetNamespace = "") eu.ehealth.db.xsd.Clinician data,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The MarkWarningAsRead method marks the warning as read in the database.
	 * It returns the warning id in the database or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "MarkWarningAsRead", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.MarkWarningAsRead")
	@WebMethod(operationName = "MarkWarningAsRead", action = "http://ehealth.eu/StorageComponent/MarkWarningAsRead")
	@ResponseWrapper(localName = "MarkWarningAsReadResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.MarkWarningAsReadResponse")
	public eu.ehealth.db.xsd.OperationResult markWarningAsRead(
			@WebParam(name = "id", targetNamespace = "") java.lang.String id,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The CreateExternalService method creates a new record for the external
	 * service using “data”. It returns the service’s identity from the database
	 * or error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "CreateExternalService", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.CreateExternalService")
	@WebMethod(operationName = "CreateExternalService", action = "http://ehealth.eu/StorageComponent/CreateExternalService")
	@ResponseWrapper(localName = "CreateExternalServiceResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.CreateExternalServiceResponse")
	public eu.ehealth.db.xsd.OperationResult createExternalService(
			@WebParam(name = "data", targetNamespace = "") eu.ehealth.db.xsd.ExternalService data,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The GetUser method receives a user’s identity (userId) and returns user’s
	 * data.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "GetUser", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetUser")
	@WebMethod(operationName = "GetUser", action = "http://ehealth.eu/StorageComponent/GetUser")
	@ResponseWrapper(localName = "GetUserResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetUserResponse")
	public eu.ehealth.db.xsd.User getUser(
			@WebParam(name = "id", targetNamespace = "") java.lang.String id);


	/**
	 * The UpdateAdministrator method updates an existing administrator record
	 * using “data”. It returns the administrator’s identity from the database
	 * or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "UpdateAdministrator", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.UpdateAdministrator")
	@WebMethod(operationName = "UpdateAdministrator", action = "http://ehealth.eu/StorageComponent/UpdateAdministrator")
	@ResponseWrapper(localName = "UpdateAdministratorResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.UpdateAdministratorResponse")
	public eu.ehealth.db.xsd.OperationResult updateAdministrator(
			@WebParam(name = "data", targetNamespace = "") eu.ehealth.db.xsd.Administrator data,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The GetClinician method selects a clinician from database using “id”.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "GetClinician", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetClinician")
	@WebMethod(operationName = "GetClinician", action = "http://ehealth.eu/StorageComponent/GetClinician")
	@ResponseWrapper(localName = "GetClinicianResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetClinicianResponse")
	public eu.ehealth.db.xsd.Clinician getClinician(
			@WebParam(name = "id", targetNamespace = "") java.lang.String id,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The GetTask method returns task by its id for the given locale.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "GetTask", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetTask")
	@WebMethod(operationName = "GetTask", action = "http://ehealth.eu/StorageComponent/GetTask")
	@ResponseWrapper(localName = "GetTaskResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetTaskResponse")
	public eu.ehealth.db.xsd.Task getTask(
			@WebParam(name = "id", targetNamespace = "") java.lang.String id,
			@WebParam(name = "locale", targetNamespace = "") eu.ehealth.db.xsd.SystemParameter locale,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The GetUserPlannedTasks method receives the user’s id, range of time
	 * (fromData, toDate) and returns the list of tasks for the user.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "GetUserPlannedTasks", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetUserPlannedTasks")
	@WebMethod(operationName = "GetUserPlannedTasks", action = "http://ehealth.eu/StorageComponent/GetUserPlannedTasks")
	@ResponseWrapper(localName = "GetUserPlannedTasksResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetUserPlannedTasksResponse")
	public java.util.List<eu.ehealth.db.xsd.Task> getUserPlannedTasks(
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId,
			@WebParam(name = "fromDate", targetNamespace = "") javax.xml.datatype.XMLGregorianCalendar fromDate,
			@WebParam(name = "toDate", targetNamespace = "") javax.xml.datatype.XMLGregorianCalendar toDate,
			@WebParam(name = "locale", targetNamespace = "") eu.ehealth.db.xsd.SystemParameter locale,
			@WebParam(name = "requesterId", targetNamespace = "") java.lang.String requesterId);


	/**
	 * The CreateUser method receives a user’s data and stores it in the
	 * database. It returns a new record’s identity or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "CreateUser", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.CreateUser")
	@WebMethod(operationName = "CreateUser", action = "http://ehealth.eu/StorageComponent/CreateUser")
	@ResponseWrapper(localName = "CreateUserResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.CreateUserResponse")
	public eu.ehealth.db.xsd.OperationResult createUser(
			@WebParam(name = "user", targetNamespace = "") eu.ehealth.db.xsd.User user);


	/**
	 * The AssingTask method receives a task’s description (task) and stores it
	 * in the database. It returns a new record’s identity or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "AssignTask", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.AssignTask")
	@WebMethod(operationName = "AssignTask", action = "http://ehealth.eu/StorageComponent/AssignTask")
	@ResponseWrapper(localName = "AssignTaskResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.AssignTaskResponse")
	public eu.ehealth.db.xsd.OperationResult assignTask(
			@WebParam(name = "task", targetNamespace = "") eu.ehealth.db.xsd.Task task,
			@WebParam(name = "locale", targetNamespace = "") eu.ehealth.db.xsd.SystemParameter locale,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The SaveCarerAssessment method receives assessment data for a carer
	 * (”assessment”), stores it in the database and returns the assessment’s
	 * identity or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "SaveCarerAssessment", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.SaveCarerAssessment")
	@WebMethod(operationName = "SaveCarerAssessment", action = "http://ehealth.eu/StorageComponent/SaveCarerAssessment")
	@ResponseWrapper(localName = "SaveCarerAssessmentResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.SaveCarerAssessmentResponse")
	public eu.ehealth.db.xsd.OperationResult saveCarerAssessment(
			@WebParam(name = "assessment", targetNamespace = "") eu.ehealth.db.xsd.CarerAssessment assessment,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The DeleteMediaContent method removes the media content from the database
	 * by its id. It returns the media content id in the database or an
	 * error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "DeleteMediaContent", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.DeleteMediaContent")
	@WebMethod(operationName = "DeleteMediaContent", action = "http://ehealth.eu/StorageComponent/DeleteMediaContent")
	@ResponseWrapper(localName = "DeleteMediaContentResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.DeleteMediaContentResponse")
	public eu.ehealth.db.xsd.OperationResult deleteMediaContent(
			@WebParam(name = "id", targetNamespace = "") java.lang.String id,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The RemoveTaskMassivelymethod removes tasks of given type for given
	 * patient for the given period of time. It returns the id of the last
	 * deleted task in the database or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "RemoveTaskMassively", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.RemoveTaskMassively")
	@WebMethod(operationName = "RemoveTaskMassively", action = "http://ehealth.eu/StorageComponent/RemoveTaskMassively")
	@ResponseWrapper(localName = "RemoveTaskMassivelyResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.RemoveTaskMassivelyResponse")
	public eu.ehealth.db.xsd.OperationResult removeTaskMassively(
			@WebParam(name = "patientId", targetNamespace = "") java.lang.String patientId,
			@WebParam(name = "typeOfTask", targetNamespace = "") java.math.BigInteger typeOfTask,
			@WebParam(name = "startDate", targetNamespace = "") javax.xml.datatype.XMLGregorianCalendar startDate,
			@WebParam(name = "endDate", targetNamespace = "") javax.xml.datatype.XMLGregorianCalendar endDate,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The CreateCarer method creates a new record for carer using “data”. It
	 * returns the carer’s identity from the database or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "CreateCarer", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.CreateCarer")
	@WebMethod(operationName = "CreateCarer", action = "http://ehealth.eu/StorageComponent/CreateCarer")
	@ResponseWrapper(localName = "CreateCarerResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.CreateCarerResponse")
	public eu.ehealth.db.xsd.OperationResult createCarer(
			@WebParam(name = "data", targetNamespace = "") eu.ehealth.db.xsd.Carer data,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The ListOfSupportedLocales method gets the list of locales that are
	 * supported by the Storage Component.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "ListOfSupportedLocales", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.ListOfSupportedLocales")
	@WebMethod(operationName = "ListOfSupportedLocales", action = "http://ehealth.eu/StorageComponent/ListOfSupportedLocales")
	@ResponseWrapper(localName = "ListOfSupportedLocalesResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.ListOfSupportedLocalesResponse")
	public java.util.List<eu.ehealth.db.xsd.SystemParameter> listOfSupportedLocales();


	/**
	 * The GetAdministrator method selects an administrator from the database
	 * using “id”.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "GetAdministrator", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetAdministrator")
	@WebMethod(operationName = "GetAdministrator", action = "http://ehealth.eu/StorageComponent/GetAdministrator")
	@ResponseWrapper(localName = "GetAdministratorResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetAdministratorResponse")
	public eu.ehealth.db.xsd.Administrator getAdministrator(
			@WebParam(name = "id", targetNamespace = "") java.lang.String id,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The GetPatientAssessments method receives the patient’s identity (“id”)
	 * and returns her/his assessment’s data or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "GetPatientAssessments", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetPatientAssessments")
	@WebMethod(operationName = "GetPatientAssessments", action = "http://ehealth.eu/StorageComponent/GetPatientAssessments")
	@ResponseWrapper(localName = "GetPatientAssessmentsResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetPatientAssessmentsResponse")
	public java.util.List<eu.ehealth.db.xsd.PatientAssessment> getPatientAssessments(
			@WebParam(name = "patientId", targetNamespace = "") java.lang.String patientId,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The GetQuestionnaire method returns the questionnaire description
	 * identified by the provided unique id.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "GetQuestionnaire", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetQuestionnaire")
	@WebMethod(operationName = "GetQuestionnaire", action = "http://ehealth.eu/StorageComponent/GetQuestionnaire")
	@ResponseWrapper(localName = "GetQuestionnaireResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetQuestionnaireResponse")
	public eu.ehealth.db.xsd.Questionnaire getQuestionnaire(
			@WebParam(name = "id", targetNamespace = "") java.lang.String id,
			@WebParam(name = "locale", targetNamespace = "") eu.ehealth.db.xsd.SystemParameter locale,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The ChangeTaskStatus method receives the task’s identity (TaskId) and the
	 * status (TaskStatus) that should be applied. It returns the task’s
	 * identity or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "ChangeTaskStatus", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.ChangeTaskStatus")
	@WebMethod(operationName = "ChangeTaskStatus", action = "http://ehealth.eu/StorageComponent/ChangeTaskStatus")
	@ResponseWrapper(localName = "ChangeTaskStatusResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.ChangeTaskStatusResponse")
	public eu.ehealth.db.xsd.OperationResult changeTaskStatus(
			@WebParam(name = "TaskId", targetNamespace = "") int taskId,
			@WebParam(name = "TaskStatus", targetNamespace = "") int taskStatus,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The UpdatePatient method updates an existing patient record using “data”.
	 * It returns the patient’s identity from the database or error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "UpdatePatient", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.UpdatePatient")
	@WebMethod(operationName = "UpdatePatient", action = "http://ehealth.eu/StorageComponent/UpdatePatient")
	@ResponseWrapper(localName = "UpdatePatientResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.UpdatePatientResponse")
	public eu.ehealth.db.xsd.OperationResult updatePatient(
			@WebParam(name = "data", targetNamespace = "") eu.ehealth.db.xsd.Patient data,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The getQuestionnaireAnswerValue method reads value for the given question
	 * for the given locale.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "getQuestionnaireAnswerValue", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetQuestionnaireAnswerValue")
	@WebMethod(action = "http://ehealth.eu/StorageComponent/getQuestionnaireAnswerValue")
	@ResponseWrapper(localName = "getQuestionnaireAnswerValueResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.GetQuestionnaireAnswerValueResponse")
	public java.lang.String getQuestionnaireAnswerValue(
			@WebParam(name = "questionId", targetNamespace = "") java.lang.String questionId,
			@WebParam(name = "value", targetNamespace = "") java.lang.String value,
			@WebParam(name = "locale", targetNamespace = "") eu.ehealth.db.xsd.SystemParameter locale);


	/**
	 * The DeletePatientAssessment method deletes an existing assessment from
	 * the database (identified by assessmentId), returns the assessment’s
	 * identity or an error-code.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "DeletePatientAssessment", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.DeletePatientAssessment")
	@WebMethod(operationName = "DeletePatientAssessment", action = "http://ehealth.eu/StorageComponent/DeletePatientAssessment")
	@ResponseWrapper(localName = "DeletePatientAssessmentResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.DeletePatientAssessmentResponse")
	public eu.ehealth.db.xsd.OperationResult deletePatientAssessment(
			@WebParam(name = "assessmentId", targetNamespace = "") java.lang.String assessmentId,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The DeleteQuestionnaire method deletes from the database the
	 * questionnaire identified by the provided unique id.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "DeleteQuestionnaire", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.DeleteQuestionnaire")
	@WebMethod(operationName = "DeleteQuestionnaire", action = "http://ehealth.eu/StorageComponent/DeleteQuestionnaire")
	@ResponseWrapper(localName = "DeleteQuestionnaireResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.DeleteQuestionnaireResponse")
	public eu.ehealth.db.xsd.OperationResult deleteQuestionnaire(
			@WebParam(name = "id", targetNamespace = "") java.lang.String id,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);


	/**
	 * The CreatePatient method creates a new record for the patient using
	 * “data”. It returns the patient’s identity from the database or an
	 * error-code. There are following error codes: “-1” Operation is not
	 * permitted “-2” Database error.
	 */
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "CreatePatient", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.CreatePatient")
	@WebMethod(operationName = "CreatePatient", action = "http://ehealth.eu/StorageComponent/CreatePatient")
	@ResponseWrapper(localName = "CreatePatientResponse", targetNamespace = "http://ehealth.eu/StorageComponent/", className = "eu.ehealth.db.storagecomponent.CreatePatientResponse")
	public eu.ehealth.db.xsd.OperationResult createPatient(
			@WebParam(name = "data", targetNamespace = "") eu.ehealth.db.xsd.Patient data,
			@WebParam(name = "userId", targetNamespace = "") java.lang.String userId);
}
