package eu.ehealth.db.db;
// Generated Oct 1, 2013 11:39:06 AM by Hibernate Tools 3.2.4.GA



/**
 * Administrator generated by hbm2java
 */
public class Administrator  implements java.io.Serializable {


     private Integer id;
     private Integer personData;
     private PersonData m_PersonData;

    public Administrator() {
    }

    public Administrator(Integer personData, PersonData m_PersonData) {
       this.personData = personData;
       this.m_PersonData = m_PersonData;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getPersonData() {
        return this.personData;
    }
    
    public void setPersonData(Integer personData) {
        this.personData = personData;
    }
    public PersonData getM_PersonData() {
        return this.m_PersonData;
    }
    
    public void setM_PersonData(PersonData m_PersonData) {
        this.m_PersonData = m_PersonData;
    }




}


