package eu.ehealth.db.db;

import java.util.HashSet;
import java.util.Set;


/**
 * AladdinUser generated by hbm2java
 */
public class AladdinUser implements java.io.Serializable
{


	private static final long serialVersionUID = 3333639572721275264L;

	private Integer id;
	private String username;
	private String password;
	private Integer type;
	private Integer personId;
	private Set Tasks = new HashSet(0);
	private Set Tasks1 = new HashSet(0);
	private Set Tasks11 = new HashSet(0);


	public AladdinUser()
	{
	}


	public AladdinUser(String username, String password, Integer type,
			Integer personId, Set Tasks, Set Tasks1, Set Tasks11)
	{
		this.username = username;
		this.password = password;
		this.type = type;
		this.personId = personId;
		this.Tasks = Tasks;
		this.Tasks1 = Tasks1;
		this.Tasks11 = Tasks11;
	}


	public Integer getId()
	{
		return this.id;
	}


	public void setId(Integer id)
	{
		this.id = id;
	}


	public String getUsername()
	{
		return this.username;
	}


	public void setUsername(String username)
	{
		this.username = username;
	}


	public String getPassword()
	{
		return this.password;
	}


	public void setPassword(String password)
	{
		this.password = password;
	}


	public Integer getType()
	{
		return this.type;
	}


	public void setType(Integer type)
	{
		this.type = type;
	}


	public Integer getPersonId()
	{
		return this.personId;
	}


	public void setPersonId(Integer personId)
	{
		this.personId = personId;
	}


	public Set getTasks()
	{
		return this.Tasks;
	}


	public void setTasks(Set Tasks)
	{
		this.Tasks = Tasks;
	}


	public Set getTasks1()
	{
		return this.Tasks1;
	}


	public void setTasks1(Set Tasks1)
	{
		this.Tasks1 = Tasks1;
	}


	public Set getTasks11()
	{
		return this.Tasks11;
	}


	public void setTasks11(Set Tasks11)
	{
		this.Tasks11 = Tasks11;
	}

}