package eu.ehealth.db.db;
// Generated Oct 1, 2013 11:39:06 AM by Hibernate Tools 3.2.4.GA



/**
 * Dict generated by hbm2java
 */
public class Dict  implements java.io.Serializable {


     private Integer id;
     private String code;
     private String description;
     private Integer locale;
     private Integer type;
     private Locale m_Locale;

    public Dict() {
    }

    public Dict(String code, String description, Integer locale, Integer type, Locale m_Locale) {
       this.code = code;
       this.description = description;
       this.locale = locale;
       this.type = type;
       this.m_Locale = m_Locale;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getLocale() {
        return this.locale;
    }
    
    public void setLocale(Integer locale) {
        this.locale = locale;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public Locale getM_Locale() {
        return this.m_Locale;
    }
    
    public void setM_Locale(Locale m_Locale) {
        this.m_Locale = m_Locale;
    }




}


