package eu.ehealth.db.db;
// Generated Oct 1, 2013 11:39:06 AM by Hibernate Tools 3.2.4.GA



/**
 * EntertainmentContent generated by hbm2java
 */
public class EntertainmentContent  implements java.io.Serializable {


     private Integer id;
     private String title;
     private String url;
     private String type;
     private String category;
     private String text;
     private Boolean enabled;

    public EntertainmentContent() {
    }

    public EntertainmentContent(String title, String url, String type, String category, String text, Boolean enabled) {
       this.title = title;
       this.url = url;
       this.type = type;
       this.category = category;
       this.text = text;
       this.enabled = enabled;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Boolean getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }




}


