package eu.ehealth.db.db;
// Generated Oct 1, 2013 11:39:06 AM by Hibernate Tools 3.2.4.GA



/**
 * ExternalService generated by hbm2java
 */
public class ExternalService  implements java.io.Serializable {


     private Integer id;
     private String Address;
     private String Description;
     private String Type;

    public ExternalService() {
    }

    public ExternalService(String Address, String Description, String Type) {
       this.Address = Address;
       this.Description = Description;
       this.Type = Type;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAddress() {
        return this.Address;
    }
    
    public void setAddress(String Address) {
        this.Address = Address;
    }
    public String getDescription() {
        return this.Description;
    }
    
    public void setDescription(String Description) {
        this.Description = Description;
    }
    public String getType() {
        return this.Type;
    }
    
    public void setType(String Type) {
        this.Type = Type;
    }




}


