package eu.ehealth.db.db;

// Generated Oct 1, 2013 11:39:06 AM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.sql.Timestamp;


/**
 * Measurement generated by hbm2java
 */
public class Measurement implements java.io.Serializable
{


	private Integer id;
	private String type;
	private BigDecimal value;
	private Timestamp datetime;
	private String units;
	private BigDecimal lowerlimit;
	private BigDecimal upperlimit;
	private Integer patientassessment;
	private Integer task;
	private PatientAssessment m_PatientAssessment;
	private Task m_Task;
	private String field1;
	private String field2;


	public Measurement()
	{
	}


	/**
	 * 
	 * @param type
	 * @param value
	 * @param datetime
	 * @param units
	 * @param lowerlimit
	 * @param upperlimit
	 * @param patientassessment
	 * @param task
	 * @param m_PatientAssessment
	 * @param m_Task
	 * @param field1
	 * @param field2
	 */
	public Measurement(String type, BigDecimal value, Timestamp datetime, String units, BigDecimal lowerlimit,
			BigDecimal upperlimit, Integer patientassessment, Integer task, PatientAssessment m_PatientAssessment,
			Task m_Task, String field1, String field2)
	{
		this.type = type;
		this.value = value;
		this.datetime = datetime;
		this.units = units;
		this.lowerlimit = lowerlimit;
		this.upperlimit = upperlimit;
		this.patientassessment = patientassessment;
		this.task = task;
		this.m_PatientAssessment = m_PatientAssessment;
		this.m_Task = m_Task;
		this.field1 = field1;
		this.field2 = field2;
	}


	public Integer getId()
	{
		return this.id;
	}


	public void setId(Integer id)
	{
		this.id = id;
	}


	public String getType()
	{
		return this.type;
	}


	public void setType(String type)
	{
		this.type = type;
	}


	public BigDecimal getValue()
	{
		return this.value;
	}


	public void setValue(BigDecimal value)
	{
		this.value = value;
	}


	public Timestamp getDatetime()
	{
		return this.datetime;
	}


	public void setDatetime(Timestamp datetime)
	{
		this.datetime = datetime;
	}


	public String getUnits()
	{
		return this.units;
	}


	public void setUnits(String units)
	{
		this.units = units;
	}


	public BigDecimal getLowerlimit()
	{
		return this.lowerlimit;
	}


	public void setLowerlimit(BigDecimal lowerlimit)
	{
		this.lowerlimit = lowerlimit;
	}


	public BigDecimal getUpperlimit()
	{
		return this.upperlimit;
	}


	public void setUpperlimit(BigDecimal upperlimit)
	{
		this.upperlimit = upperlimit;
	}


	public Integer getPatientassessment()
	{
		return this.patientassessment;
	}


	public void setPatientassessment(Integer patientassessment)
	{
		this.patientassessment = patientassessment;
	}


	public Integer getTask()
	{
		return this.task;
	}


	public void setTask(Integer task)
	{
		this.task = task;
	}


	public PatientAssessment getM_PatientAssessment()
	{
		return this.m_PatientAssessment;
	}


	public void setM_PatientAssessment(PatientAssessment m_PatientAssessment)
	{
		this.m_PatientAssessment = m_PatientAssessment;
	}


	public Task getM_Task()
	{
		return this.m_Task;
	}


	public void setM_Task(Task m_Task)
	{
		this.m_Task = m_Task;
	}
	
	
	/**
	 * @return the field1
	 */
	public String getField1()
	{
		return field1;
	}

	
	/**
	 * @param field1 the field1 to set
	 */
	public void setField1(String field1)
	{
		this.field1 = field1;
	}


	/**
	 * @return the field2
	 */
	public String getField2()
	{
		return field2;
	}

	
	/**
	 * @param field2 the field2 to set
	 */
	public void setField2(String field2)
	{
		this.field2 = field2;
	}


}
