package eu.ehealth.db.db;
// Generated Oct 1, 2013 11:39:06 AM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Patient generated by hbm2java
 */
public class Patient  implements java.io.Serializable {


     private Integer id;
     private Integer persondata;
     private Integer sd;
     private Integer clinician;
     private String swname;
     private String swphone;
     private String swemail;
     private String ccname;
     private String ccphone;
     private String ccemail;
     private String gpname;
     private String gpphone;
     private String gpemail;
     private Integer carer;
     private Set Warnings = new HashSet(0);
     private Set PatientAssessments = new HashSet(0);
     private PersonData m_PersonData;
     private SocioDemographicData m_SocioDemographicData;
     private Clinician m_Clinician;
     private Carer m_Carer;

    public Patient() {
    }

    public Patient(Integer persondata, Integer sd, Integer clinician, String swname, String swphone, String swemail, String ccname, String ccphone, String ccemail, String gpname, String gpphone, String gpemail, Integer carer, Set Warnings, Set PatientAssessments, PersonData m_PersonData, SocioDemographicData m_SocioDemographicData, Clinician m_Clinician, Carer m_Carer) {
       this.persondata = persondata;
       this.sd = sd;
       this.clinician = clinician;
       this.swname = swname;
       this.swphone = swphone;
       this.swemail = swemail;
       this.ccname = ccname;
       this.ccphone = ccphone;
       this.ccemail = ccemail;
       this.gpname = gpname;
       this.gpphone = gpphone;
       this.gpemail = gpemail;
       this.carer = carer;
       this.Warnings = Warnings;
       this.PatientAssessments = PatientAssessments;
       this.m_PersonData = m_PersonData;
       this.m_SocioDemographicData = m_SocioDemographicData;
       this.m_Clinician = m_Clinician;
       this.m_Carer = m_Carer;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getPersondata() {
        return this.persondata;
    }
    
    public void setPersondata(Integer persondata) {
        this.persondata = persondata;
    }
    public Integer getSd() {
        return this.sd;
    }
    
    public void setSd(Integer sd) {
        this.sd = sd;
    }
    public Integer getClinician() {
        return this.clinician;
    }
    
    public void setClinician(Integer clinician) {
        this.clinician = clinician;
    }
    public String getSwname() {
        return this.swname;
    }
    
    public void setSwname(String swname) {
        this.swname = swname;
    }
    public String getSwphone() {
        return this.swphone;
    }
    
    public void setSwphone(String swphone) {
        this.swphone = swphone;
    }
    public String getSwemail() {
        return this.swemail;
    }
    
    public void setSwemail(String swemail) {
        this.swemail = swemail;
    }
    public String getCcname() {
        return this.ccname;
    }
    
    public void setCcname(String ccname) {
        this.ccname = ccname;
    }
    public String getCcphone() {
        return this.ccphone;
    }
    
    public void setCcphone(String ccphone) {
        this.ccphone = ccphone;
    }
    public String getCcemail() {
        return this.ccemail;
    }
    
    public void setCcemail(String ccemail) {
        this.ccemail = ccemail;
    }
    public String getGpname() {
        return this.gpname;
    }
    
    public void setGpname(String gpname) {
        this.gpname = gpname;
    }
    public String getGpphone() {
        return this.gpphone;
    }
    
    public void setGpphone(String gpphone) {
        this.gpphone = gpphone;
    }
    public String getGpemail() {
        return this.gpemail;
    }
    
    public void setGpemail(String gpemail) {
        this.gpemail = gpemail;
    }
    public Integer getCarer() {
        return this.carer;
    }
    
    public void setCarer(Integer carer) {
        this.carer = carer;
    }
    public Set getWarnings() {
        return this.Warnings;
    }
    
    public void setWarnings(Set Warnings) {
        this.Warnings = Warnings;
    }
    public Set getPatientAssessments() {
        return this.PatientAssessments;
    }
    
    public void setPatientAssessments(Set PatientAssessments) {
        this.PatientAssessments = PatientAssessments;
    }
    public PersonData getM_PersonData() {
        return this.m_PersonData;
    }
    
    public void setM_PersonData(PersonData m_PersonData) {
        this.m_PersonData = m_PersonData;
    }
    public SocioDemographicData getM_SocioDemographicData() {
        return this.m_SocioDemographicData;
    }
    
    public void setM_SocioDemographicData(SocioDemographicData m_SocioDemographicData) {
        this.m_SocioDemographicData = m_SocioDemographicData;
    }
    public Clinician getM_Clinician() {
        return this.m_Clinician;
    }
    
    public void setM_Clinician(Clinician m_Clinician) {
        this.m_Clinician = m_Clinician;
    }
    public Carer getM_Carer() {
        return this.m_Carer;
    }
    
    public void setM_Carer(Carer m_Carer) {
        this.m_Carer = m_Carer;
    }




}


