package eu.ehealth.db.db;
// Generated Oct 1, 2013 11:39:06 AM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * QuestionnaireQuestion generated by hbm2java
 */
public class QuestionnaireQuestion  implements java.io.Serializable {


     private Integer id;
     private String type;
     private Boolean isPrimary;
     private Integer parentid;
     private String title;
     private Integer quest;
     private Integer condition;
     private Boolean deleted;
     private Integer position;
     private Integer GlobalId;
     private QuestionnaireQuestion m_QuestionnaireQuestion;
     private Questionnaire m_Questionnaire;
     private Set QuestionnaireQuestionAnswers = new HashSet(0);
     private Set QuestionnaireAnswers = new HashSet(0);

    public QuestionnaireQuestion() {
    }

    public QuestionnaireQuestion(String type, Boolean isPrimary, Integer parentid, String title, Integer quest, Integer condition, Boolean deleted, Integer position, Integer GlobalId, QuestionnaireQuestion m_QuestionnaireQuestion, Questionnaire m_Questionnaire, Set QuestionnaireQuestionAnswers, Set QuestionnaireAnswers) {
       this.type = type;
       this.isPrimary = isPrimary;
       this.parentid = parentid;
       this.title = title;
       this.quest = quest;
       this.condition = condition;
       this.deleted = deleted;
       this.position = position;
       this.GlobalId = GlobalId;
       this.m_QuestionnaireQuestion = m_QuestionnaireQuestion;
       this.m_Questionnaire = m_Questionnaire;
       this.QuestionnaireQuestionAnswers = QuestionnaireQuestionAnswers;
       this.QuestionnaireAnswers = QuestionnaireAnswers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Boolean getIsPrimary() {
        return this.isPrimary;
    }
    
    public void setIsPrimary(Boolean isPrimary) {
        this.isPrimary = isPrimary;
    }
    public Integer getParentid() {
        return this.parentid;
    }
    
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Integer getQuest() {
        return this.quest;
    }
    
    public void setQuest(Integer quest) {
        this.quest = quest;
    }
    public Integer getCondition() {
        return this.condition;
    }
    
    public void setCondition(Integer condition) {
        this.condition = condition;
    }
    public Boolean getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
    public Integer getPosition() {
        return this.position;
    }
    
    public void setPosition(Integer position) {
        this.position = position;
    }
    public Integer getGlobalId() {
        return this.GlobalId;
    }
    
    public void setGlobalId(Integer GlobalId) {
        this.GlobalId = GlobalId;
    }
    public QuestionnaireQuestion getM_QuestionnaireQuestion() {
        return this.m_QuestionnaireQuestion;
    }
    
    public void setM_QuestionnaireQuestion(QuestionnaireQuestion m_QuestionnaireQuestion) {
        this.m_QuestionnaireQuestion = m_QuestionnaireQuestion;
    }
    public Questionnaire getM_Questionnaire() {
        return this.m_Questionnaire;
    }
    
    public void setM_Questionnaire(Questionnaire m_Questionnaire) {
        this.m_Questionnaire = m_Questionnaire;
    }
    public Set getQuestionnaireQuestionAnswers() {
        return this.QuestionnaireQuestionAnswers;
    }
    
    public void setQuestionnaireQuestionAnswers(Set QuestionnaireQuestionAnswers) {
        this.QuestionnaireQuestionAnswers = QuestionnaireQuestionAnswers;
    }
    public Set getQuestionnaireAnswers() {
        return this.QuestionnaireAnswers;
    }
    
    public void setQuestionnaireAnswers(Set QuestionnaireAnswers) {
        this.QuestionnaireAnswers = QuestionnaireAnswers;
    }




}


