package eu.ehealth.db.db;
// Generated Oct 1, 2013 11:39:06 AM by Hibernate Tools 3.2.4.GA


import java.sql.Timestamp;

/**
 * QuestionnaireAnswer generated by hbm2java
 */
public class QuestionnaireAnswer  implements java.io.Serializable {


     private Integer id;
     private Integer question;
     private String value;
     private Integer UserId;
     private Timestamp dateTime;
     private Integer objectId;
     private QuestionnaireQuestion m_QuestionnaireQuestion;

    public QuestionnaireAnswer() {
    }

    public QuestionnaireAnswer(Integer question, String value, Integer UserId, Timestamp dateTime, Integer objectId, QuestionnaireQuestion m_QuestionnaireQuestion) {
       this.question = question;
       this.value = value;
       this.UserId = UserId;
       this.dateTime = dateTime;
       this.objectId = objectId;
       this.m_QuestionnaireQuestion = m_QuestionnaireQuestion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Integer question) {
        this.question = question;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Integer getUserId() {
        return this.UserId;
    }
    
    public void setUserId(Integer UserId) {
        this.UserId = UserId;
    }
    public Timestamp getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Timestamp dateTime) {
        this.dateTime = dateTime;
    }
    public Integer getObjectId() {
        return this.objectId;
    }
    
    public void setObjectId(Integer objectId) {
        this.objectId = objectId;
    }
    public QuestionnaireQuestion getM_QuestionnaireQuestion() {
        return this.m_QuestionnaireQuestion;
    }
    
    public void setM_QuestionnaireQuestion(QuestionnaireQuestion m_QuestionnaireQuestion) {
        this.m_QuestionnaireQuestion = m_QuestionnaireQuestion;
    }




}


