package eu.ehealth.db.db;

// Generated Oct 1, 2013 11:39:06 AM by Hibernate Tools 3.2.4.GA

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;


/**
 * SocioDemographicData generated by hbm2java
 */
public class SocioDemographicData implements java.io.Serializable
{


	private Integer id;
	private Integer Gender;
	private Integer MaritalStatus;
	private Integer Children;
	private Integer LivingWith;
	private Timestamp birthday;
	private Integer height;
	private Set Carers = new HashSet(0);
	private Set Patients = new HashSet(0);


	public SocioDemographicData()
	{
	}


	/**
	 * 
	 * @param Gender
	 * @param MaritalStatus
	 * @param Children
	 * @param LivingWith
	 * @param birthday
	 * @param Carers
	 * @param Patients
	 * @param height
	 */
	public SocioDemographicData(Integer Gender, Integer MaritalStatus, Integer Children, Integer LivingWith,
			Timestamp birthday, Set Carers, Set Patients, Integer height)
	{
		this.Gender = Gender;
		this.MaritalStatus = MaritalStatus;
		this.Children = Children;
		this.LivingWith = LivingWith;
		this.birthday = birthday;
		this.Carers = Carers;
		this.Patients = Patients;
		this.height = height;
	}


	public Integer getId()
	{
		return this.id;
	}


	public void setId(Integer id)
	{
		this.id = id;
	}


	public Integer getGender()
	{
		return this.Gender;
	}


	public void setGender(Integer Gender)
	{
		this.Gender = Gender;
	}


	public Integer getHeight()
	{
		return this.height;
	}


	public void setHeight(Integer height)
	{
		this.height = height;
	}


	public Integer getMaritalStatus()
	{
		return this.MaritalStatus;
	}


	public void setMaritalStatus(Integer MaritalStatus)
	{
		this.MaritalStatus = MaritalStatus;
	}


	public Integer getChildren()
	{
		return this.Children;
	}


	public void setChildren(Integer Children)
	{
		this.Children = Children;
	}


	public Integer getLivingWith()
	{
		return this.LivingWith;
	}


	public void setLivingWith(Integer LivingWith)
	{
		this.LivingWith = LivingWith;
	}


	public Timestamp getBirthday()
	{
		return this.birthday;
	}


	public void setBirthday(Timestamp birthday)
	{
		this.birthday = birthday;
	}


	public Set getCarers()
	{
		return this.Carers;
	}


	public void setCarers(Set Carers)
	{
		this.Carers = Carers;
	}


	public Set getPatients()
	{
		return this.Patients;
	}


	public void setPatients(Set Patients)
	{
		this.Patients = Patients;
	}

}
