package eu.ehealth.db.db;
// Generated Oct 1, 2013 11:39:06 AM by Hibernate Tools 3.2.4.GA



/**
 * SystemParameter generated by hbm2java
 */
public class SystemParameter  implements java.io.Serializable {


     private Integer id;
     private String Code;
     private String Description;

    public SystemParameter() {
    }

    public SystemParameter(String Code, String Description) {
       this.Code = Code;
       this.Description = Description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCode() {
        return this.Code;
    }
    
    public void setCode(String Code) {
        this.Code = Code;
    }
    public String getDescription() {
        return this.Description;
    }
    
    public void setDescription(String Description) {
        this.Description = Description;
    }




}


