package eu.ehealth.db.db;
// Generated Oct 1, 2013 11:39:06 AM by Hibernate Tools 3.2.4.GA


import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Task generated by hbm2java
 */
public class Task  implements java.io.Serializable {


     private Integer id;
     private Integer TaskType;
     private Timestamp DateTimeAssigned;
     private Timestamp DateTimeFulfilled;
     private Integer TaskStatus;
     private String url;
     private String text;
     private Integer questionnaire;
     private Integer Executor;
     private Integer Assigner;
     private Integer Object;
     private Questionnaire m_Questionnaire;
     private AladdinUser m_AladdinUser;
     private AladdinUser m_AladdinUser1;
     private AladdinUser m_AladdinUser11;
     private Set Measurements = new HashSet(0);

    public Task() {
    }

    public Task(Integer TaskType, Timestamp DateTimeAssigned, Timestamp DateTimeFulfilled, Integer TaskStatus, String url, String text, Integer questionnaire, Integer Executor, Integer Assigner, Integer Object, Questionnaire m_Questionnaire, AladdinUser m_AladdinUser, AladdinUser m_AladdinUser1, AladdinUser m_AladdinUser11, Set Measurements) {
       this.TaskType = TaskType;
       this.DateTimeAssigned = DateTimeAssigned;
       this.DateTimeFulfilled = DateTimeFulfilled;
       this.TaskStatus = TaskStatus;
       this.url = url;
       this.text = text;
       this.questionnaire = questionnaire;
       this.Executor = Executor;
       this.Assigner = Assigner;
       this.Object = Object;
       this.m_Questionnaire = m_Questionnaire;
       this.m_AladdinUser = m_AladdinUser;
       this.m_AladdinUser1 = m_AladdinUser1;
       this.m_AladdinUser11 = m_AladdinUser11;
       this.Measurements = Measurements;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getTaskType() {
        return this.TaskType;
    }
    
    public void setTaskType(Integer TaskType) {
        this.TaskType = TaskType;
    }
    public Timestamp getDateTimeAssigned() {
        return this.DateTimeAssigned;
    }
    
    public void setDateTimeAssigned(Timestamp DateTimeAssigned) {
        this.DateTimeAssigned = DateTimeAssigned;
    }
    public Timestamp getDateTimeFulfilled() {
        return this.DateTimeFulfilled;
    }
    
    public void setDateTimeFulfilled(Timestamp DateTimeFulfilled) {
        this.DateTimeFulfilled = DateTimeFulfilled;
    }
    public Integer getTaskStatus() {
        return this.TaskStatus;
    }
    
    public void setTaskStatus(Integer TaskStatus) {
        this.TaskStatus = TaskStatus;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Integer getQuestionnaire() {
        return this.questionnaire;
    }
    
    public void setQuestionnaire(Integer questionnaire) {
        this.questionnaire = questionnaire;
    }
    public Integer getExecutor() {
        return this.Executor;
    }
    
    public void setExecutor(Integer Executor) {
        this.Executor = Executor;
    }
    public Integer getAssigner() {
        return this.Assigner;
    }
    
    public void setAssigner(Integer Assigner) {
        this.Assigner = Assigner;
    }
    public Integer getObject() {
        return this.Object;
    }
    
    public void setObject(Integer Object) {
        this.Object = Object;
    }
    public Questionnaire getM_Questionnaire() {
        return this.m_Questionnaire;
    }
    
    public void setM_Questionnaire(Questionnaire m_Questionnaire) {
        this.m_Questionnaire = m_Questionnaire;
    }
    public AladdinUser getM_AladdinUser() {
        return this.m_AladdinUser;
    }
    
    public void setM_AladdinUser(AladdinUser m_AladdinUser) {
        this.m_AladdinUser = m_AladdinUser;
    }
    public AladdinUser getM_AladdinUser1() {
        return this.m_AladdinUser1;
    }
    
    public void setM_AladdinUser1(AladdinUser m_AladdinUser1) {
        this.m_AladdinUser1 = m_AladdinUser1;
    }
    public AladdinUser getM_AladdinUser11() {
        return this.m_AladdinUser11;
    }
    
    public void setM_AladdinUser11(AladdinUser m_AladdinUser11) {
        this.m_AladdinUser11 = m_AladdinUser11;
    }
    public Set getMeasurements() {
        return this.Measurements;
    }
    
    public void setMeasurements(Set Measurements) {
        this.Measurements = Measurements;
    }




}


