package eu.ehealth.db.db;
// Generated Oct 1, 2013 11:39:06 AM by Hibernate Tools 3.2.4.GA



/**
 * Translate generated by hbm2java
 */
public class Translate  implements java.io.Serializable {


     private Integer id;
     private Integer entityid;
     private String entity;
     private Integer locale;
     private String value;
     private Locale m_Locale;

    public Translate() {
    }

    public Translate(Integer entityid, String entity, Integer locale, String value, Locale m_Locale) {
       this.entityid = entityid;
       this.entity = entity;
       this.locale = locale;
       this.value = value;
       this.m_Locale = m_Locale;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getEntityid() {
        return this.entityid;
    }
    
    public void setEntityid(Integer entityid) {
        this.entityid = entityid;
    }
    public String getEntity() {
        return this.entity;
    }
    
    public void setEntity(String entity) {
        this.entity = entity;
    }
    public Integer getLocale() {
        return this.locale;
    }
    
    public void setLocale(Integer locale) {
        this.locale = locale;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Locale getM_Locale() {
        return this.m_Locale;
    }
    
    public void setM_Locale(Locale m_Locale) {
        this.m_Locale = m_Locale;
    }




}


