package eu.ehealth.db.db;

// Generated Oct 1, 2013 11:39:06 AM by Hibernate Tools 3.2.4.GA

import java.sql.Timestamp;


/**
 * Warning generated by hbm2java
 */
public class Warning implements java.io.Serializable
{


	private Integer id;
	private Integer TypeOfWarning;
	private Timestamp DateTimeOfWarning;
	private Integer Effect;
	private Integer Indicator;
	private Integer RiskLevel;
	private String JustificationText;
	private Integer EmergencyLevel;
	private Boolean Delivered;
	private Integer Patient;
	private Patient m_Patient;


	public Warning()
	{
	}


	public Warning(Integer TypeOfWarning, Timestamp DateTimeOfWarning,
			Integer Effect, Integer Indicator, Integer RiskLevel,
			String JustificationText, Integer EmergencyLevel,
			Boolean Delivered, Integer Patient, Patient m_Patient)
	{
		this.TypeOfWarning = TypeOfWarning;
		this.DateTimeOfWarning = DateTimeOfWarning;
		this.Effect = Effect;
		this.Indicator = Indicator;
		this.RiskLevel = RiskLevel;
		this.JustificationText = JustificationText;
		this.EmergencyLevel = EmergencyLevel;
		this.Delivered = Delivered;
		this.Patient = Patient;
		this.m_Patient = m_Patient;
	}


	public Integer getId()
	{
		return this.id;
	}


	public void setId(Integer id)
	{
		this.id = id;
	}


	public Integer getTypeOfWarning()
	{
		return this.TypeOfWarning;
	}


	public void setTypeOfWarning(Integer TypeOfWarning)
	{
		this.TypeOfWarning = TypeOfWarning;
	}


	public Timestamp getDateTimeOfWarning()
	{
		return this.DateTimeOfWarning;
	}


	public void setDateTimeOfWarning(Timestamp DateTimeOfWarning)
	{
		this.DateTimeOfWarning = DateTimeOfWarning;
	}


	public Integer getEffect()
	{
		return this.Effect;
	}


	public void setEffect(Integer Effect)
	{
		this.Effect = Effect;
	}


	public Integer getIndicator()
	{
		return this.Indicator;
	}


	public void setIndicator(Integer Indicator)
	{
		this.Indicator = Indicator;
	}


	public Integer getRiskLevel()
	{
		return this.RiskLevel;
	}


	public void setRiskLevel(Integer RiskLevel)
	{
		this.RiskLevel = RiskLevel;
	}


	public String getJustificationText()
	{
		return this.JustificationText;
	}


	public void setJustificationText(String JustificationText)
	{
		this.JustificationText = JustificationText;
	}


	public Integer getEmergencyLevel()
	{
		return this.EmergencyLevel;
	}


	public void setEmergencyLevel(Integer EmergencyLevel)
	{
		this.EmergencyLevel = EmergencyLevel;
	}


	public Boolean getDelivered()
	{
		return this.Delivered;
	}


	public void setDelivered(Boolean Delivered)
	{
		this.Delivered = Delivered;
	}


	public Integer getPatient()
	{
		return this.Patient;
	}


	public void setPatient(Integer Patient)
	{
		this.Patient = Patient;
	}


	public Patient getM_Patient()
	{
		return this.m_Patient;
	}


	public void setM_Patient(Patient m_Patient)
	{
		this.m_Patient = m_Patient;
	}

}
